### ISSUE TITLE
"Install the DS4 Driver" Error

### ISSUE THREAD

**Issue by skeyewalking** [Jays2Kings/DS4Windows#349]
DS4Windows ->Settings -> Controller/Driver Setup -> Install the DS4 Driver

"Unhandled exception has occurred in your application. If I click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately

Could not find file "C:\....\ScpDriver.log"

I clicked Continue and it just showed me the same thing again.

Details : 

> See` the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
>
>************** Exception Text **************
>System.IO.FileNotFoundException: Could not find file 'C:\Users\Isay Bart\Documents\ScpDriver.log'.
File name: 'C:\Users\Isay Bart\Documents\ScpDriver.log'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at DS4Windows.WelcomeDialog.timer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

>************** Loaded Assemblies **************
>mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
>----------------------------------------
>DS4Windows
    Assembly Version: 1.4.222.0
    Win32 Version: 1.4.222
    CodeBase: file:///C:/Users/Isay%20Bart/Documents/DS4Windows.exe
>----------------------------------------
>System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
>----------------------------------------
>System.Windows.Forms
    Assembly Version: 4.0.0.0

Any fix for this?
I already have my DS4 connected via USB and the light on the controller is off.

Thanks in advance!

**Comment by OlivierAlc1** [comment]
I believe that since the website isn’t working, the download from within the Ds4 won’t work. I say just check now and then if the website is up.

**Comment by lebanony** [comment]
got the same problem and I donut now what to do
