### ISSUE TITLE
Unhandled exception when toggling 'Hide DS4 Controller'

### ISSUE THREAD

**Issue by andrwmorph** [Jays2Kings/DS4Windows#39]
I get the following error when I attempt to toggle 'Hide DS4 Controller'

I'm using Windows 7.

![image](https://cloud.githubusercontent.com/assets/1325229/9019234/64b774fe-37b6-11e5-862f-4b5e143ff888.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.ProcessManager.GetModuleInfos(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at DS4Windows.DS4Form.hideDS4CheckBox_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Thanks!

**Comment by Jays2Kings** [comment]
This issue should now be fixed in version 1.4.269

**Comment by andrwmorph** [comment]
Confirmed as fixed. Thanks!
